// <auto-generated />
namespace Garage2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Display_name_for_regnumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Display_name_for_regnumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201510231332178_Display_name_for_regnumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
