// <auto-generated />
namespace Garage2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addtablesvehicletypemembernewseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablesvehicletypemembernewseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201510291049560_add tables vehicletype, member, new seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
